### ISSUE TITLE
[Tool][crossmint-mint] Doesn't mint to email well

### ISSUE THREAD

**Issue by alfonso-paella** [goat-sdk/goat#140]
**Describe the bug**

This prompt:
`Mint 1 NFT to recipient test@gmail.com. The NFT's collection id is ${collectionId} and the NFT's metadata are ${JSON.stringify(metadata)}`

should mint an NFT to this email, but I ran it three times with gpt 4o-mini and it always tries to send it to <chain>:<email_address>, which is incorrect

The problem is the tool schema is taking a mint locator directly, where it should just take "email" as a parameter, and then construct the locator under the hood, to make it easier for the LLM

**Comment by 0xaguspunk** [comment]
Solved here: https://github.com/goat-sdk/goat/pull/142
