### ISSUE TITLE
Change plugin "sendETH" to "sendEVMNetworkToken"

### ISSUE THREAD

**Issue by muttoni** [goat-sdk/goat#17]
**Is your feature request related to a problem? Please describe it.**

Currently GOAT supports all EVM chains, but some EVM chains don't use Ether as their network token. therefore the function name of the `sendETH` is inappropriately named.

Since currently when supporting a non Ether-native chain, I could either use the plugin sendETH (not clear) or I could duplicate the function to sendXYZ (not ideal, since code duplication).

File in question: `src/plugins/send-eth.ts`

**Describe the solution you'd like**

I propose to rename the `sendETH` function in "@goat-sdk/core" to something like `sendEVMNetworkToken` or `sendNativeEVMToken` or something similar. 

Happy to file a PR and update the tutorials if this sounds good,.

**Describe alternatives you've considered**

I could either use the plugin sendETH (not clear when reading the code), or I could duplicate the plugin to sendXYZ (not ideal, since unnecessary code duplication).

**Additional context**

**Comment by 0xaguspunk** [comment]
Right.. we spoke about this a bit but never ended up addressing it.

My concern with `sendNativeEVMToken` is that the LLM won't be able to understand if it needs to use that action when prompted with something like `Send 0.001 ETH to 0x123` or `Send 0.001 POL to 0x123` (the POL one is already a problem probably) because it's kind of a generic description.

Maybe a better approach would be to figure out a way to programmatically get the native token of the chain (you can already get that for EVM by looking at the viem chain object) and update the `sendNativeToken` description and name of the tool accordingly.

So if the wallet client is in Polygon it will return a `sendNativeToken` function but the name of the tool will be `send_pol` and the description will say `This {{tool}} allows you to send POL to an EVM/Polygon address`

We could also put SOL and other non-EVM chains in this bucket, but we would need to create an object that stores the native token (the same way viem has it for EVM chains)

Would you be up for exploring this? 🙂

**Comment by muttoni** [comment]
Makes a lot of sense! Let me tinker on this

**Comment by muttoni** [comment]
How's something like this to start?

`src/plugins/send-native-token.ts`

```ts
import { parseEther } from "viem";
import type { WalletClient } from "viem";
import { z } from "zod";
import type { EVMWalletClient } from "../wallets";
import type { Plugin } from "./plugins";

export function sendNativeToken(walletClient: WalletClient): Plugin<EVMWalletClient> {

    const nativeToken = walletClient?.chain?.nativeCurrency.symbol;
    const chainName = walletClient?.chain?.name;

    return {
        name: `send_${nativeToken?.toLowerCase()}`,
        supportsSmartWallets: () => true,
        supportsChain: (chain) => chain.type === "evm",
        getTools: async () => {
            const toolName = `send_${nativeToken?.toLowerCase()}`;
            const description = `This {{tool}} sends ${nativeToken} to an address on ${chainName}.`;

            return [
                {
                    name: toolName,
                    description,
                    parameters: sendNativeTokenParametersSchema,
                    method: sendNativeTokenMethod,
                },
            ];
        },
    };
}

const sendNativeTokenParametersSchema = z.object({
    to: z.string().describe("The address to send the native token to"),
    amount: z.string().describe("The amount of the native token to send"),
});

async function sendNativeTokenMethod(
    walletClient: EVMWalletClient,
    parameters: z.infer<typeof sendNativeTokenParametersSchema>,
): Promise<string> {
    try {
        const amount = parseEther(parameters.amount);
        const tx = await walletClient.sendTransaction({
            to: parameters.to,
            value: amount,
        });

        return tx.hash;
    } catch (error) {
        throw new Error(`Failed to send native token: ${error}`);
    }
}
```

and then would be called like so:

```ts
(async () => {
	const tools = await getOnChainTools({
		wallet: viem(walletClient),
		plugins: [
			sendNativeToken(walletClient), // requires passing in the wallet client to the plugin
		],
	});

	const result = await generateText({
		model: openai("gpt-4o-mini"),
		tools: tools,
		maxSteps: 5,
		prompt: "Send 1 IP to 0x862E77b3Da6Faae318BeEf6D26Bb02f96dF1afbb",
	});
...
```

It's not general purpose (e.g. Solana) just yet, but at least for EVM it makes the native token dynamic, and could replace sendETH.ts. LMK if I can PR it or not!

**Comment by 0xaguspunk** [comment]
Nice! yes, def I think this is the right direction!

Two things:
1. The [chain returned by the wallet](https://github.com/goat-sdk/goat/blob/main/typescript/packages/core/src/wallets/core.ts#L16) client doesn't include the token info. You'd need to get the token info based on the chain id you have. One way would be importing all chains from `viem` and looping to find the chain based on the network id.
2. No need to pass the wallet client. Get tools already gets passed the chain. We will make a future change to core where plugins get the walletclient directly

**Comment by muttoni** [comment]
Forgive me, but I'm not understanding point 1 lol (i'm slow) - currently I'm not using the chain object you linked to. I'm using the viem wallet client object that I'm passing into the plugin when calling it, and it contains the token info (i.e. console logging the variables below works fine, and I've tested the implementation above btw). 

``` 
    const nativeToken = walletClient?.chain?.nativeCurrency.symbol;
    const chainName = walletClient?.chain?.name;
```

2. Got it - but if I rely only on getTools having walletClient context, I won't be able to customize the plugin `name` right? (see commented line below)

```ts 
export function sendNativeToken(walletClient: WalletClient): Plugin<EVMWalletClient> {

    const nativeToken = walletClient?.chain?.nativeCurrency.symbol;
    const chainName = walletClient?.chain?.name;

    return {
        name: `send_${nativeToken?.toLowerCase()}`, // if I rely on getTools, I won't have this available here. 
        supportsSmartWallets: () => true,
        supportsChain: (chain) => chain.type === "evm",
        getTools: async () => {
            const toolName = `send_${nativeToken?.toLowerCase()}`;
            const description = `This {{tool}} sends ${nativeToken} to an address on ${chainName}.`;

            return [
                {
                    name: toolName,
                    description,
                    parameters: sendNativeTokenParametersSchema,
                    method: sendNativeTokenMethod,
                },
            ];
        },
    };
}

```

**Comment by 0xaguspunk** [comment]
1. Ah damn haha `WalletClient` from viem not from goat. Then yes, but would only work for viem, not for custodial wallets from crossmint, solana, etc. You'd need to use the [WalletClient from goat](https://github.com/goat-sdk/goat/blob/main/typescript/packages/core/src/wallets/core.ts#L29) and use `getChain` to make it generic. Then you need to do what I mentioned before
2. The plugin of the name has 0 effect on the prompts, it's just used for logging/debugging so it'd be ok! :)

**Comment by 0xaguspunk** [comment]
@muttoni we fixed this: https://github.com/goat-sdk/goat/blob/main/typescript/packages/core/src/core-plugins/send-eth.ts

We are missing updating the name of the function which will come in the next core upgrade we are planning :)

**Comment by muttoni** [comment]
Nice! Sorry got sidetracked and never sent a PR. Thanks for following up :)
